name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Build
      run: |
        # https://github.com/alan-turing-institute/ptype-dmkd/issues/14
        ./build/build.sh /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
