name: build-test-publish

on:
  push:
    branches:
      - release

jobs:
  main:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1 # needed for twine
      with:
        python-version: '3.8'
    - name: Build, test and publish to PyPI
      run: |
        script/do-build-test-publish.sh ${which python} ${{ secrets.pypi_password }} pypi
