name: build

on:
  push:
    branches:
      - '!release'

  pull_request:
    branches:
      - '!release'

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Build
      run: |
        # https://github.com/alan-turing-institute/ptype-dmkd/issues/14
        script/do.sh /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python script/build.sh
