name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Build
      run: |
        # https://github.com/alan-turing-institute/ptype-dmkd/issues/14
        script/build.sh /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  publish:
    if: contains(github.ref, "release")
    runs-on: macos-10.15
      needs: build
      steps:
      - uses: actions/checkout@v2
      - name: Publish to PyPI
        run: |
          # https://github.com/alan-turing-institute/ptype-dmkd/issues/14
          script/publish.sh ${{ secrets.pypi_password }} /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python
