name: build-publish

on:
  push:
    branches:
      - release

  pull_request:
    branches:
      - release

jobs:
  build-publish:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1 # needed for twine
      with:
        python-version: '3.8'
    - name: Publish to PyPI
      run: |
        # https://github.com/alan-turing-institute/ptype-dmkd/issues/14
        script/do.sh /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python script/build-publish.sh ${{ secrets.pypi_password }}
